### ISSUE TITLE
セントラル側のpythonコードについて

### ISSUE THREAD

**Issue by qoopen0815** [naoki-sawada/m5stack-ble#1]
RaspberryPi4（セントラル）とM5Stack（ペリフェラル）間のBLE通信を構築するために、
@naoki-sawada さんが書かれた[こちら](https://qiita.com/nsawa/items/2afd4ae9c10af87d0133)の記事を読ませていただきました。

非常にわかりやすく、ペリフェラル側の処理については問題なく組むことができました。
しかし、RPi4でセントラル側の処理を実装しようとしたときに、
公開されている[デモコード](https://github.com/naoki-sawada/m5stack-ble/blob/nodejs/python-client/main.py)が下記のエラーで実行できずに困っております。

```bash
( ^q^) < nodejs[1] )
pi@raspberrypi: ~/gitprojects/m5stack-ble/python-client
>> sudo python3 main.py 
Using adapter: raspberrypi
Disconnecting any connected devices...
Searching device...
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    ble.run_mainloop_with(main)
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_BluefruitLE-0.9.9-py3.7.egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 105, in run_mainloop_with
  File "/usr/local/lib/python3.7/dist-packages/future-0.18.2-py3.7.egg/future/utils/__init__.py", line 441, in raise_
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_BluefruitLE-0.9.9-py3.7.egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 120, in _user_thread_main
  File "main.py", line 33, in main
    device = ble.find_device(name="m5-stack")
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_BluefruitLE-0.9.9-py3.7.egg/Adafruit_BluefruitLE/interfaces/provider.py", line 135, in find_device
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_BluefruitLE-0.9.9-py3.7.egg/Adafruit_BluefruitLE/interfaces/provider.py", line 114, in find_devices
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_BluefruitLE-0.9.9-py3.7.egg/Adafruit_BluefruitLE/bluez_dbus/device.py", line 150, in name
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: No such property 'Name'
````

色々調べて回っているのですが、
なかなか解決の糸口が見つけられず困っている状況なのでご助力いただければと思います。
よろしくお願いします。

**Comment by naoki-sawada** [comment]
Adafruit_Python_BluefruitLEはdeprecatedとのことでした
https://github.com/adafruit/Adafruit_Python_BluefruitLE/issues/39#issuecomment-672935495

PythonのClientをBleakに置き換えました(#2)ので、こちらをお使いください

**Comment by qoopen0815** [comment]
@naoki-sawada 
対応ありがとうございます！
こちらの環境でも正常に動作しました！

目的を達成したのでこちらのissueはcloseさせていただきます！
ありがとうございました。
